apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: shubhamjain2908/history
          env:
            - name: NATS_CLUSTER_ID
              value: "hackernewshub"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: MONGO_URI
              value: "mongodb://history-mongo-srv:27017/history"
---
apiVersion: v1
kind: Service
metadata:
  name: history-srv
spec:
  selector:
    app: history
  ports:
    - name: history
      protocol: TCP
      port: 3000
      targetPort: 3000
