apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: tickethub.dev
      http:
        paths:
          - path: /top-stories/?(.*)
            backend:
              serviceName: stories-srv
              servicePort: 3000
          - path: /past-stories/?(.*)
            backend:
              serviceName: history-srv
              servicePort: 3000
